spring:
  application:
    name: WeatherDiary

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/weatherdiary
    username: root
    password: ${DATASOURCE_PASSWORD}

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

open-weather-map:
  base-url: https://api.openweathermap.org/data/2.5/weather
  default-city: seoul
  api-key: ${OPENWEATHERMAP_APIKEY}